name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Cache Dependencies
        run: deno cache deps.ts

      - name: Run Format
        run: deno fmt --check

      - name: Build Deno Module
        run: deno run --reload mod.ts

      - name: Run Tests
        run: deno test -A
